FROM mcr.microsoft.com/vscode/devcontainers/python:3.9
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /workspaces
COPY requirements.txt .
RUN sudo apt-get update
RUN sudo apt --only-upgrade install ca-certificates
RUN python -m pip install -r requirements.txt 
USER vscode