FROM mcr.microsoft.com/vscode/devcontainers/python:3.8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /workspaces
COPY requirements.txt .
RUN python -m pip install -r requirements.txt 
USER vscode